Feature branch
shubham14p3/Building-Blocks-Bubble-Sort pull request #1
Opened 2020-04-03 08:20 UTC by shubham14p3

Created our first bubble sort project in ruby
We had two modules as per requirement
#bubble_sort
#bubble_sort_by

Inputs for the same are as follow :
a. #bubble_sort
array = [5,9,7,3,1]
bubble_sort(array)

b. #bubble_sort_by
array = ["hi","hello","hey"]
bubble_sort_by(array) do |left,right|
right.length - left.length
end

Output for the above were as follow:-

a. #bubble_sort
This is the array that needs to be sorted : [5, 9, 7, 3, 1]
[1, 3, 5, 7, 9]

b. #bubble_sort_by
This is the array that needs to be sorted : ["hi", "hello", "hey"]
["hi", "hey", "hello"]

2020-04-03 14:00 UTC, shubham14p3 commented
The earlier Repo &  Code was deleted and closed, as we were unable to enable linters 
Previous Pull Request : .https://github.com/shubham14p3/Advanced-Building-Blocks-Bubble-Sort/pull/2
Changes were made and have been updated for the same.

2020-04-03 17:38 UTC, kobiyoyo requested changes
## Hi Team  ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, you are almost there .
### General


- [ ] `bubble_sort_by`
 `bubble_sort_by(["hi","hello","hey"]) do |left,right|`
    `left.length - right.length`
  `end`
 ` => should return ["hi", "hey", "hello"]`
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-04-03 17:38 UTC, kobiyoyo commented on sort_by.rb
> +  puts array.to_s
i recommend you remove the `puts` and `to_s ` .it should be like this `array`

2020-04-03 17:38 UTC, kobiyoyo commented on sort_by.rb
> +  puts array.to_s
i recommend you remove the `puts` and `to_s ` .it should be like this `array`

2020-04-03 19:18 UTC, shubham14p3 commented on sort_by.rb
> +  puts array.to_s
Made the changes

2020-04-03 19:18 UTC, shubham14p3 commented on sort_by.rb
> +  puts array.to_s
Made the changes

2020-04-03 19:19 UTC, shubham14p3 commented
Kindly let me know if any thing else is required.

2020-04-06 08:04 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello, Thank you for the improvements you've done.
However, there is still a bug. Take a look at this execution
```ruby
2.6.5 :002 > bubble_sort_by(["hi","hello","hey"]) do |left,right|
2.6.5 :003 >     left.length - right.length
2.6.5 :004?>   end
 => ["hello", "hey", "hi"] 
2.6.5 :005 >
```
According to the [project description](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks), the result must be 
```ruby
=> ["hi", "hey", "hello"]
```

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

2020-04-06 11:33 UTC, shubham14p3 commented
Error Fixed

2020-04-06 13:17 UTC, majovanilla commented
Hey @shubham14p3 

## You did a *great* job on this project! 💜 

Your bubble_sort meets all the requirements asked by previous TSE's.
Your pull request message is perfect! :fire: 

## You are approved to merge

Happy coding 🤓

--Maria Reyes

2020-04-06 14:38 UTC, shubham14p3 commented
Changes Made & Code approved,
Thanks

2020-04-06 14:39 UTC, merged